### ISSUE TITLE
Automate preprocessing steps to create master db table

### ISSUE THREAD

**Issue by perrygeo** [Ecotrust/aez-viewer#14]
Going from the raw GIS outputs (dbfs, lookup tables, etc) to a single master table with all subzone information

**Comment by rhodges** [comment]
![img_20140731_160039_606](https://cloud.githubusercontent.com/assets/526505/3782632/24f2d18c-19a4-11e4-8f58-aef27b20a9b4.jpg)

**Comment by rhodges** [comment]
Works with Jon's data and aggregating subzones into zones here: 136b7df1d2df163b366f3836003f6509724842fd
Beginning testing with lookup table for outputting regions.
Still need to work on also outputting subzone data.

**Comment by rhodges** [comment]
Super-subzones work as planned: e3a03162ec7159ebaa3e21cc4cb997434edc87b0

**Comment by rhodges** [comment]
I'm closing this - the process works for what's ready - little details like #13 will sort themselves out via tickets
