### ISSUE TITLE
Script to output (geo)jsons for web interface [4 hours]

### ISSUE THREAD

**Issue by perrygeo** [Ecotrust/aez-viewer#15]
Using the master db table, aggregate as needed, create temp tables and output the proper static files to drive the web interface.

**Comment by rhodges** [comment]
Good for 'Crop', need to figure out needs of 'Zone'

**Comment by rhodges** [comment]
Currently zone just runs on food_zones.geojson (formerly 'food_zones_all.geojson', fixed in f267560b8cc0367174aae985a4e6fe29152965cd). This is generated by the scripts and is now running as planned. This will be revisited if we need it to be more responsive.
