### ISSUE TITLE
Create crop table and add to process [1 day]

### ISSUE THREAD

**Issue by perrygeo** [Ecotrust/aez-viewer#16]
Crop table should define the subset of crops we're interested in displaying plus any crop-specific, non-geographic data for the "explore by crop"

Columns will be defined according to the needs of #3 

We'll need to incorporate this table into the processing steps of #15

**Comment by rhodges** [comment]
While #3 has some big plans that we're still waiting on, this actually gets defined in create_zone_table.py by the 'measures [ ]' and 'types { }' variables. For now this seems easier and more flexible than a new table.

**Comment by rhodges** [comment]
Dupe of #3 at this point.
