### ISSUE TITLE
GeoJSON for web should web mercator

### ISSUE THREAD

**Issue by perrygeo** [Ecotrust/aez-viewer#18]
projection should be the native web projection epsg:3857

Not sure where in the process we need to fix this. 

Client side will need to be adjusted to not do reprojection

**Comment by rhodges** [comment]
Reprojecting to 3857 is easy - there's a setting in create_zone_table.py to do exactly that. Also, by default, the leaflet map is 3857, HOWEVER:
Leaflet actually enforces inputs be in 4326. It's all manners of messed up, but everything I can find indicates that you are expected to reproject any non-4326 data before handing it over to Leaflet, regardless of what CRS you give in the map layer's definition.

http://stackoverflow.com/questions/22504251/set-map-center-in-leaflet-with-3857-lat-lon#23012355
http://bost.ocks.org/mike/leaflet/
http://www.quora.com/Web-Development/Why-are-coordinates-in-Leaflet-in-degrees-if-it-uses-the-Google-Mercator-coordinate-reference-system
