### ISSUE TITLE
Humanize numbers [4 hours]

### ISSUE THREAD

**Issue by rhodges** [Ecotrust/aez-viewer#24]
100000 -> 100,000 or 100k or 0.1 million, probably 100,000
.000005 -> "<0.001", NOT "5.0 x 10^(-6)"

a javascript tool probably already exists for this.

**Comment by perrygeo** [comment]
This one looks promising: https://github.com/HubSpot/humanize#numbers

**Comment by rhodges** [comment]
This is getting close to complete - just needs a few more tweaks and "less sciency" eyes on it.

**Comment by rhodges** [comment]
Will keep a vigilant eye out for this.
