### ISSUE TITLE
By Zone: Legend for Crop Colors [4 hours]

### ISSUE THREAD

**Issue by rhodges** [Ecotrust/aez-viewer#28]
We need a legend to identify which colors in the histogram pertain to which crop types.

Assigned to Matt because he's done all of the "By Zone" work, but can just as easily be done by @rhodges .

**Comment by rhodges** [comment]
https://github.com/mbostock/d3/wiki/Ordinal-Scales

**Comment by perrygeo** [comment]
closed via 0da5cb9f9cf84f2483f2e059be41353cb646d10a
