### ISSUE TITLE
Document data processing steps for aez viewer

### ISSUE THREAD

**Issue by perrygeo** [Ecotrust/aez-viewer#45]
We will eventually need to reproduce the analysis and/or write up a methods section for a report. We need a document (office 365? terra? wiki? TBD) that describes the data processing from raw data to finished product.

**Comment by rhodges** [comment]
The document handling process is currently in the GitHub wiki: https://github.com/Ecotrust/aez-viewer/wiki/Data-Workflow
Generating the data that went into the .dbfs and generating the zones/regions was done beforehand by Mike, Jon, and Jocelyn.
