### ISSUE TITLE
Load license point data into viewer. 

### ISSUE THREAD

**Issue by jtutak** [Ecotrust/aez-viewer#69]
If point datasets can be turned on and off, then load all 10 shapefiles here:
\Terra\GIS\projects\Projects2014\FoodHub_FoodSystems\Data\Processed\Ag\ODAlicenses\Viewer\
AND
\Terra\GIS\projects\Projects2014\FoodHub_FoodSystems\Data\Processed\infr\ColdStorage_ODA_OFB.shp

If they can't, let me know and I will merge them into fewer datasets for easier visualization. 

The spreadsheet that explains which point datasets should link to which category or product is here: \Terra\GIS\projects\Projects2014\FoodHub_FoodSystems\Data\Processed\Ag\ODAlicenses\ODALicense_crosswalk.xlsx

**Comment by rhodges** [comment]
complete: 97ecf861ed8ab68eb90ad80c283bb6c60d564e2f
