### ISSUE TITLE
Add "Plums & Prunes" county data

### ISSUE THREAD

**Issue by jtutak** [Ecotrust/aez-viewer#70]
Please add the county-level data for plums and prunes to the viewer (location below). Let me know if you'd like it in another format. 

\Terra\GIS\projects\Projects2014\FoodHub_FoodSystems\Data\Source\Ag\AgCensus\AgCensus2012_fromJon\TBLfn_UPDATE.csv

**Comment by rhodges** [comment]
Complete: 16165d25c062e4b148afdf15cf3697e6b6894642
