### ISSUE TITLE
Remove county-level data with no values. 

### ISSUE THREAD

**Issue by jtutak** [Ecotrust/aez-viewer#71]
I've gone through the data and identified products that aren't documented in Oregon. Not sure what the easiest way to pull them out of the viewer is; I made a spreadsheet of what needs to go (path below), but if there's an easier format let me know. 

\Terra\GIS\projects\Projects2014\FoodHub_FoodSystems\Data\Processed\Ag\AgCensus2012\AgCensus_limiteddatalist.xlsx

**Comment by rhodges** [comment]
@jtutak : I'm hitting an error with fc29 "Sunflower Seed, All" in that it's not defined in the crosswalk, but it currently does have data being pulled out of our dbfs and is therefore showing up when the tool is trying to process the data.

Should I remove anything not in the crosswalk?

**Comment by jtutak** [comment]
Hrrrmm. I know that the products I listed in AgCensus_limiteddatalist.xlsx /are/ in the crosswalk; I don't know why something /with/ data wouldn't be in the crosswalk. 

If it's easy to compile a list what has data but isn't in the crosswalk, that would be helpful. If not, I can take a look tomorrow.

**Comment by rhodges** [comment]
I have everything matching the crosswalk for now.
The updated crosswalk (with the unneccesary crops removed) is here:
https://github.com/Ecotrust/aez-viewer/blob/livestock/site/food_zones/input/AgCensus_FoodHub_category_crosswalk.csv

**Comment by rhodges** [comment]
Ignoring "Sunflower Seed, All" (it seems to be the only case) for now. Will see if anyone complains.
