### ISSUE TITLE
Standardize & organize drop down menu

### ISSUE THREAD

**Issue by jtutak** [Ecotrust/aez-viewer#72]
- [x] Some products should be renamed for clarity. I've added a column ("rename") identifying which ones in: \Terra\GIS\projects\Projects2014\FoodHub_FoodSystems\Data\Processed\Ag\AgCensus2012AgCensus_FoodHub_category_crosswalk.xlsx
- [x] Have the products listed alphabetically within each category, if possible.

**Comment by rhodges** [comment]
Complete: d1d434d000b3f9f603940b5b60454572793d6c36
